# Generated by Django 4.0.3 on 2022-03-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_django', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bloggero',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Lector',
        ),
    ]
